version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambientese
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: grupo5
      JWT_SECRET: GCJrc9*tnU(Y73E@SD&VIHqN  # Defina isso conforme necessário
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ambientese?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EMAIL: your_email@example.com  # Defina isso conforme necessário
      EMAIL_HOST: smtp.example.com  # Defina isso conforme necessário
      EMAIL_PORT: 587  # Defina isso conforme necessário
      EMAIL_APP_PASSWORD: your_email_app_password  # Defina isso conforme necessário
    depends_on:
      - db

volumes:
  mysql-data:
